#ifndef HEADER_FGE_ERROR
#define HEADER_FGE_ERROR

typedef enum FGEError FGEError;

enum FGEError
{
    FGE_E_NONE = 0,
    FGE_E_SUCCESS = 1,
    FGE_E_INIT_FAIL = 2,
    FGE_E_OUT_OF_MEMORY = 3,
    FGE_E_WRONG_SIZE = 4,
    FGE_E_SHADER_COMPILE = 5,
    FGE_E_CONTAINER_LIMIT = 6,
    FGE_E_CONTAINER_OUTSIDE_RANGE = 7,
    FGE_E_CONTAINER_EMPTY = 8,
    FGE_E_NULL = 9
};

#endif